### PR TITLE
Remove legacy java code

### PR DESCRIPTION
**Pull request by jblebrun**
Blocked by: cl/321408692

### CODE REVIEW

**Comment by piotrswigon** [comment]
We will soon start dusting off web-bits and embedding them in the new architecture in Android, so the question arises how does this code that's being removed here relates to that.

My intuition is that embedding Web-bits as an ArcHost will be different enough that we will want start from scratch and revisit various design questions rather than refactor what we had. Given this I am ok-ish with this PR, and the code lives in git history obviously.

I would also add @cromwellian to comment and check if his intuition is the same.

**Comment by jblebrun** [comment]
My argument in favor is that a lot has changed since that code was last used; if we want to use ideas in this code, it should be re-introduced in new PRs, written in Kotlin, along with copious amounts of documentation, and re-reviewed by the team.

**Comment by piotrswigon** [comment]
I understand and sympathise with this reasoning. Approving.

**Comment by shaper** [comment]
@piotrswigon has already noted my comments, I agree that given it's in revision history we're good, and it's nice to remove the tax of having the code around in the meantime.

**Pull request merged**
