### PR TITLE
Arcs API and primitive builtin ingestion particle

### PR DESCRIPTION
**Pull request by mmandlis**

### CODE REVIEW

**Comment by mmandlis** [comment]
i'm hoping i didn't mess up the formatting...

**Comment by mmandlis** [comment]
i talked to Shane and Berni offline and i'll be updating the builtin particles design and implementation, please, don't review yet.

**Comment by cromwellian** [comment]
I think it'l go through several iterations between it's idiomatic for
Android/AiAi. For example, working with raw JSON directly is non-idiomatic.
AiAi developers would probably prefer to use @AutoValue based APIs, so we'd
probably have some tool that generates AutoValue classes and stubs to
implement, e.g. stuff like

arcsApi.ingest(Person.builder().name("Ray").source("com.foo.bar").build())

Then you'd have a method probably like

<T> registerHandler(Class<T> clazz, Function<T, String>) { ... }

And use class literal registeration/lookup.

Java/Kotlin particles could then read typed handles and get back
deserialized entities with normal fields/accessors.

**Comment by cromwellian** [comment]
Deleted comment.

**Comment by mmandlis** [comment]
refactored according to offline discussion (will update the design doc shortly), closing this PR in favor of https://github.com/PolymerLabs/arcs/pull/3475

**Pull request closed without merging**
