### PR TITLE
Convert Bytes to typescript

### PR DESCRIPTION
**Pull request by lindner**

### CODE REVIEW

**Comment by lindner** [comment]
1st of many typescript PRs....

**Comment by shaper** [comment]
This is the Arcs-system schema/manifest type name and so it's intended to be an Arcs-developer-facing term. Would we really want Arcs developers to have to use `Uint8Array`? I'm open to that possibility but am inferring that since it's noted as a TypeScript PR maybe you thought this was not external-dev-facing and was just a TypeScript-oriented cleanup.

Also if we do rename we'd probably want to revise the [parser](https://github.com/PolymerLabs/arcs/blob/master/runtime/manifest-parser.peg#L1059) at the same time to match.

See the lightweight [Blobs design doc](https://docs.google.com/document/d/1245YKcJHaQEZxCQw2ozzFyyPl31_mSup8azqDOeVCSs/edit) for more background.

**Comment by lindner** [comment]
Aha, that makes a lot more sense.  Will adjust

**Comment by lindner** [comment]
PTAL?

**Pull request merged**
