### PR TITLE
New SlotComposer implementation...

### PR DESCRIPTION
**Pull request by mmandlis**
supporting new recipe format and new slot related APIs

DISCLAIMER:
- this is still work in progress (and some files are for local testing only, they have "please ignore" message on top, please, ignore)
- slot related tests are commented out, i need to fix them
- some implementation details are quite ugly, i want to fix them once we agree on the high level

### CODE REVIEW

**Comment by shans** [comment]
I don't understand everything that's going on here, but the bits I understand look pretty good!

**Comment by mmandlis** [comment]
Thanks Shane! Let's talk about all the less clear bits tomorrow.

**Comment by mmandlis** [comment]
UPDATE

Shane and I looked the changes today and I addressed all comments that we agreed on.

Scott, can you, please, take a look too? And/or we can discuss it at the meeting tomorrow.

Doug and I are (almost?) ready to submit both our changes,.. break everything and then fix it. 
We can either wait for Monday or do it tomorrow (let's discuss at meeting in the morning)?

**Comment by sjmiles** [comment]
This is a major inflection point, so don't worry about breaking everything. I have old revisions if I need a _classic_ version, let's advance #master asap. 

One question:  how to interpret the "PLEASE IGNORE" sections? They also say "DO NOT SUBMIT", and I don't know what that means.

**Comment by mmandlis** [comment]
Doug, I pulled your change and rebased.
I need someone to approve this so I can commit (it is somewhat broken, i'm fixing it in parallel).

**Pull request merged**
