### PR TITLE
Remove localData copy from the database driver, to free up some memor…

### PR DESCRIPTION
**Pull request by galganif**
…y, it is only used on first receiver registration

### CODE REVIEW

**Comment by ianull** [comment]
Nice work! We are getting close to memory footprint target.

There is one bug? we need to fix/figure out before checking in this change, otherwise the latency may have a notable regression.

Screen Shot 2020-05-05 at 11 01 48 AM
Every handle.store(entity) will create a new Backing Store which in turn calls DatabaseDriver:registerReceiver() that will always call getDatabaseData() with this change. 
From the code, 
suspend fun store(id: String) = storeMutex.withLock {
        stores.getOrPut(id) {
            setupStore(id)
        }
    }
Different entity reference id would spin up a new Store even if it's with the same handle.
This is also why I observed growing StoreRecord at class BackingStore and never got freed (http://b/154865157)

**Comment by galganif** [comment]
> Nice work! We are getting close to memory footprint target.
> 
> There is one bug? we need to fix/figure out before checking in this change, otherwise the latency may have a notable regression.
> 
> Screen Shot 2020-05-05 at 11 01 48 AM
> 
> Every handle.store(entity) will create a new Backing Store which in turn calls DatabaseDriver:registerReceiver() that will always call getDatabaseData() with this change.
> 
> From the code,
> `suspend fun store(id: String) = storeMutex.withLock { stores.getOrPut(id) { setupStore(id) } }`
> 
> Different entity reference id would spin up a new Store even if it's with the same handle.
> 
> This is also why I observed growing StoreRecord at class BackingStore and never got freed (http://b/154865157)

Yes we need a new store for each entity/ref being stored. BackingStore takes care of that. This is by design and this change does not affect it.

There may be some latency increase: with this change registerReceiver always goes to the database. So it may be slower on first creation, but I think it is unavoidable if we want to get rid of this in-memory copy.

**Comment by ianull** [comment]
What does the "first creation" mean? Currently the every handle.store() acts like the first creation to me.

Say
handleA.store(SomeEntity())
handleA.store(SomeEntity())

The two store() calls on the handleA trigger two DatabaseDriver:registerReceiver().
Is this expected?

Say
val entity = SomeEntity()
handleA.store(entity)
entity.xxx = yyy // manipulation of fields, not sure if it's allowed
handleA.store(entity)

How many DatabaseDriver:registerReceiver() are expected?

**Comment by ianull** [comment]
Also wondering is it possible to just change/update the object reference in DatabaseDriver to refer to that one in BackingStore? Prefer to finding a win-win.

**Comment by galganif** [comment]
I mean first creation of each entity.

For example:
val entity1 = SomeEntity()
handleA.store(entity1)
val entity2 = SomeOtherEntityOfTheSameType()
handleA.store(entity2)

in this case we expect two backing stores, each one with a separate driver instance, ie two setupStore() and two registerReceiver() calls. The two registerReceiver calls are on two different driver objects, not on the same driver (each database driver only handles one backing storageKey, each entity has a separate backing storage key).


entity.xxx = yyy // manipulation of fields
this I think at the moment should talk to the existing driver (ie there is an existing store in stores in backingstore), so no registerReceiver call in this case.

Again, none of this is changed by this pr. Do you have any specific concerns with this pr?

**Comment by ianull** [comment]
Nope, the PR is good to get in :-)
I just need to keep eyes on every improvement, regression as well as tradeoff in behind.

**Comment by galganif** [comment]
> Nope, the PR is good to get in :-)
> I just need to keep eyes on every improvement, regression as well as tradeoff in behind.

Yes you are right. Let me know if you find this introduces a latency regression. I think it won't as registerReceiver would be called on a new driver (ie null local model) in most of the cases.

**Pull request merged**
