### PR TITLE
Updates Javaharness instructions

### PR DESCRIPTION
**Pull request by csilvestrini**
Also added .bazelproject file to make it easier to get started.

### CODE REVIEW

**Comment by jasonwyatt** [comment]
I'm seeing the following issues when syncing the project using ASwB

```
Warning:Sync was successful, but there were Bazel build errors. The project may not be fully updated or resolve until fixed. If the errors are from your working set, please uncheck 'Bazel > Sync > Expand Sync to Working Set' and try again.
/usr/local/google/home/jwf/github/arcs/javaharness/.bazelproject
    Error:Error:no targets found beneath 'javaharness/java/arcs/pipes-shell'
ERROR
    Error:Error:/usr/local/google/home/jwf/github/arcs/WORKSPACE:40:1: //external:android/sdk depends on @androidsdk//:sdk in repository @androidsdk which failed to fetch. no such package '@androidsdk//': Either the path attribute of android_sdk_repository or the ANDROID_HOME environment variable must be set.
    Error:Error:/usr/local/google/home/jwf/github/arcs/WORKSPACE:40:1: //external:android/dx_jar_import depends on @androidsdk//:dx_jar_import in repository @androidsdk which failed to fetch. no such package '@androidsdk//': Either the path attribute of android_sdk_repository or the ANDROID_HOME environment variable must be set.
    Error:Error:command succeeded, but there were errors parsing the target pattern```

**Comment by jasonwyatt** [comment]
@cromwellian suggested I do the following:
> try bazel clean --expunge if the android build is failing, also make sure you have Android 29 installed in $ANDROID_HOME

That resolved the ANDROID_HOME issues, but there is still an issue it's encountering:

```
Warning:Sync was successful, but there were Bazel build errors. The project may not be fully updated or resolve until fixed. If the errors are from your working set, please uncheck 'Bazel > Sync > Expand Sync to Working Set' and try again.
/usr/local/google/home/jwf/github/arcs/javaharness/.bazelproject
    Error:Error:no targets found beneath 'javaharness/java/arcs/pipes-shell'
ERROR
    Error:Error:command succeeded, but there were errors parsing the target pattern
/usr/local/google/home/jwf/github/arcs/javaharness/java/arcs/api/SingletonProxy.java
    Warning:Warning:No package name string found in java source file: /usr/local/google/home/jwf/github/arcs/javaharness/java/arcs/api/SingletonProxy.java
```

**Comment by jasonwyatt** [comment]
Turns out I just needed to RTFM and run build.sh

**Comment by csilvestrini** [comment]
Added small troubleshooting section for the errors Jason came across

**Pull request merged**
