### PR TITLE
Make `sigh lint` not pick up any additional eslint config files

### PR DESCRIPTION
**Pull request by dstockwell**

### CODE REVIEW

**Comment by dstockwell** [comment]
I added a couple more commits to enable no-undef and fix/skip the resulting errors. I turned on all the environments we use and whitelisted a bunch of globals that were non-trival to fix. The result is that we get much better but not perfect coverage, eg. you could reference a global `it` anywhere, despite that really only making sense in a unit test.

**Comment by dstockwell** [comment]
Hah, @shaper you beat me to it. Presumably because of the way we use importScripts, there are a bunch of undefined references in Words, like `Tile` etc.

**Comment by dstockwell** [comment]
I'm just going to land the first change in this series, and move the remainder to #909

**Comment by sjmiles** [comment]
Was OOO yesterday, LGTM.

**Pull request merged**
