### PR TITLE
Ignore log files from sigh watch

### PR DESCRIPTION
**Pull request by Cypher1**
Maybe we should do something more clever than having a regex but I'm happy to keep updating it as I find things that aren't expected.

### CODE REVIEW

**Comment by mykmartin** [comment]
I wonder if a positive filter might work better? Something like `*.{js,ts,json,arcs,manifest,...}`

Here's the list of file extensions that exist under `src`:

arcs, cc, cgtest, fcfg, gitignore, h, html, js, json, jsonld, kt, manifest, md, npmrc, pegjs, png, recipe, recipes, schema, ts

**Review by mykmartin — APPROVED** [review]

**Comment by Cypher1** [comment]
I think a combination of positive and negative filters is what's needed for best coverage.

@mykmartin I've changed this to ignore all `.log` files (as I realised there are sometimes .files that are used for config that could change test outcomes).

**Comment by mykmartin** [comment]
SGTM

**Comment by Cypher1** [comment]
@bgogul Can I get a merge (thanks in advance)

**Pull request merged**
