### PR TITLE
Rename strategizer directory to planning

### PR DESCRIPTION
**Pull request by raulverag**
tools/sigh test passes.

This just renames the directory and fixes everything pointing to it. Subsequent PRs will actually move files.

### CODE REVIEW

**Comment by raulverag** [comment]
Maria, I'm planning to move arcs/runtime/ts/plan/*.ts into arcs/planning/ts/, without the "plan", (did I just really write that?) so there won't be any duplication or confusion. i.e. it's intended to all go to the one folder.

**Comment by raulverag** [comment]
Paul, I'm intending to create a planning/ts folder for ts files, just like runtime has, and adjusting the build script. I can't do this separation while keeping all the ts in runtime/ts. Is there a problem with that?

**Comment by lindner** [comment]
I think planning should be the first typescript only directory, which will simplify a number of things.  Would appreciate landing my PR first as it really changes a lot of things.

Will add you as a reviewer

**Comment by raulverag** [comment]
SGTM, Paul. When do you think it will be ready?

**Comment by raulverag** [comment]
And in the meantime, _this_ PR is just renaming the directory. No files are being moved yet, and it's ready now. Let's submit this one now.

**Comment by piotrswigon** [comment]
LGTM FWIW.

**Comment by raulverag** [comment]
Paul's PR makes this obsolete. More TS infrastructure work is needed, which is coming in another PR.

**Pull request closed without merging**
