### PR TITLE
Upgrade to Kotlin 1.3.70 and latest rules_kotlin

### PR DESCRIPTION
**Pull request by cromwellian**

### CODE REVIEW

**Comment by cromwellian** [comment]
I just moved the maven_install call up.  rules_kotlin now depends on rules_jvm_external, and you get a cycle error complaint if it is declared after rules_kotlin. Ditto for rules_proto.

**Comment by bayesianmind** [comment]
Looking at the history of Kotlin versioning internally it appears to be ~2 weeks after release, so we're about 6 days away from internal updating to 1.3.70 if history holds.

**Comment by cromwellian** [comment]
I can leave this PR for testing and we can land when they switch. I'm interested in the affects it has on GCB performance. Also, I need to test re-enabling JS builds.

**Comment by cromwellian** [comment]
Weird that tools/local-presubmit works, but on GCB it fails 
```
ERROR: /usr/src/app/java/arcs/sdk/android/storage/service/testutil/BUILD:7:1: //java/arcs/sdk/android/storage/service/testutil:testutil_kt depends on @com_github_jetbrains_kotlin//:kotlin-stdlib in repository @com_github_jetbrains_kotlin which failed to fetch. no such package '@com_github_jetbrains_kotlin//': java.io.IOException: Error downloading [https://github.com/JetBrains/kotlin/releases/download/v1.3.70/kotlin-compiler-1.3.70.zip] to /root/.cache/bazel/_bazel_root/a14564dce24fc232216f1aef117728d1/external/com_github_jetbrains_kotlin/kotlin-compiler-1.3.70.zip: Checksum was 709d782ff707a633278bac4c63bab3026b768e717f8aaf62de1036c994bc89c7 but wanted 12f97cff23ff8116904cb97a7ef4e3af5c3b8e5df9d9e63baa251d9a73b42fbb
Step #3 - "local-presubmit": ERROR: Analysis of target '//java/arcs/sdk/android/storage/service/testutil:testutil' failed; build aborted: no such package '@com_github_jetbrains_kotlin//': java.io.IOException: Error downloading [https://github.com/JetBrains/kotlin/releases/download/v1.3.70/kotlin-compiler-1.3.70.zip] to /root/.cache/bazel/_bazel_root/a14564dce24fc232216f1aef117728d1/external/com_github_jetbrains_kotlin/kotlin-compiler-1.3.70.zip: Checksum was 709d782ff707a633278bac4c63bab3026b768e717f8aaf62de1036c994bc89c7 but wanted 12f97cff23ff8116904cb97a7ef4e3af5c3b8e5df9d9e63baa251d9a73b42fbb
Step #3 - "local-presubmit":
```

It seems GCB can't download from this GitHub url. I'm gonna try 1.3.60 to see if it is related to the new rules_kotlin implementation using a different downloader.

**Comment by cromwellian** [comment]
> 709d782ff707a633278bac4c63bab3026b768e717f8aaf62de1036c994bc89c7

oops, never mind, it' the SHA

**Comment by cromwellian** [comment]
> I'm super excited about 1.3.70, but internal hasn't switched to 1.3.70 yet. If we upgrade in OSS before that it could easily lead to nasty build breaks.
> See cs query `f:third_party/kotlin/kotlin/BUILD` for the current authoritative google3 version.
> Talk internally sounds like they will upgrade fairly soon.

1.3.70 is now live on G3 as the default.  Let's goooooooo. :)

**Pull request merged**
