### PR TITLE
don't render empty model

### PR DESCRIPTION
**Pull request by mmandlis**

### CODE REVIEW

**Comment by sjmiles** [comment]
Why? Populated model is not actually required. I did recently change things to not render if there is no `template` (iirc), which is deterministic.

**Comment by mmandlis** [comment]
> Why? Populated model is not actually required to render a template. I did recently change things to not render if there is no `template` (iirc), which is deterministic.

I'm getting 2 `notification` render messages for the same particle slot in the Android demo: the one i expect and another with `content":{"template":"","model":{}}`

**Comment by sjmiles** [comment]
My fix for filtering empty templates may not have landed yet, I'll track it down.

**Comment by mmandlis** [comment]
> My fix for filtering empty templates may not have landed yet, I'll track it down.

closing this and fixing the current issue with: https://github.com/PolymerLabs/arcs/pull/3752
will revisit later. thanks!

**Pull request closed without merging**
