### PR TITLE
override the global planificator with the current arc's planificator

### PR DESCRIPTION
**Pull request by mmandlis**

### CODE REVIEW

**Comment by piotrswigon** [comment]
The only issue is that this overwrites the reference on web-planner creation, but you may have multiple arcs and switch between them. Is it easy to get to the global planificator? Or planificator of another arc?

This is probably better than what's there now, so LGTM.

**Comment by mmandlis** [comment]
> The only issue is that this overwrites the reference on web-planner creation, but you may have multiple arcs and switch between them. Is it easy to get to the global planificator? Or planificator of another arc?
> 
> This is probably better than what's there now, so LGTM.

I think, I only ever want the planificator of the arc i'm currently looking at, at least this is consistent with the `arc` global (that is similarly accessible in the console). Maybe worth adding some planificator related stuff to the extension? I'll think about it, also let me know if you have any ideas of what could be useful.

**Comment by piotrswigon** [comment]
WDYT about having an object with planificators:

```
  window.planificators[arc.id] = planificator;
```

or:

```
  window.planificators.global = planificator;
```

**Comment by piotrswigon** [comment]
I haven't used the planificator in the console, so I don't know what's useful.

**Comment by piotrswigon** [comment]
Ok, I'm fine with that.

**Pull request merged**
