### PR TITLE
add an identifer to Thing

### PR DESCRIPTION
**Pull request by smalls**

### CODE REVIEW

**Comment by shans** [comment]
What's the identifier for? I wonder if we should be starting to think about the API we're going to use to expose IDs instead of this?

Related, I think - are we interested in moving across to the actual schema.org schemas rather than hand-rolled ones?

**Comment by smalls** [comment]
I'm using it to store placesId from the Places API, specifically to match results from the places autocomplete and search APIs. I chose 'identifier' since it's part of schema.org/Thing, and one of the intended uses is for UUIDs so it seemed not terrible - although let me know if you see a better solution?

**Comment by smalls** [comment]
(And on the related note, yes - we have #450 filed in the next milestone to move to schema.org references directly).

**Comment by shans** [comment]
That seems quite reasonable, thanks for following up.

At some point we might need to think about whether things like UUIDs really do belong in the schema.org identifier field or whether we should allow ID generation to make use of existing unique keys like this, but that point isn't now :)

**Comment by smalls** [comment]
Of course!

That's an interesting thought. Some more thinking around this might be helpful especially if we begin to collect results from multiple data sources - for instance, right now identifier holds the placesId for me, but should my arcs entity be tied to an OpenTable restaurant id as well? Having arcs id generation take all of that into account might be a seamless way for developers to ignore that complexity.

**Pull request merged**
