### PR TITLE
Move ktlint into `sigh lint`

### PR DESCRIPTION
**Pull request by csilvestrini**
Makes ktlint run over all files, not just the ones which changed.
* `tools/sigh lint` now calls `ktlint` as one of its linters
* The `--fix` arg works to make ktlint autofix whatever it can
* `tools/ktlint` has been deleted (it would just invoke ktlint on files you have changed in your commit)
* The `tools/ktlint` step on Travis has been deleted. There is already a separate step for `tools/sigh lint` which will now do the same check

### CODE REVIEW

**Comment by bgogul** [comment]
It looks like the PR removes the lint check. Don't we still want it?

**Comment by csilvestrini** [comment]
> It looks like the PR removes the lint check. Don't we still want it?

It doesn't actually remove the lint check. I added an explanation in the PR description above. Does that explain it?

**Comment by bgogul** [comment]
> > It looks like the PR removes the lint check. Don't we still want it?
> 
> It doesn't actually remove the lint check. I added an explanation in the PR description above. Does that explain it?

Ah, I see you made it check all the .kt files instead of just the ones that changed.

**Comment by bgogul** [comment]
> Ah, I see you made it check all the .kt files instead of just the ones that changed.

Actually, this can be annoying,  if `ktlint` behavior changes often. However, that should be rare.

**Comment by csilvestrini** [comment]
> > Ah, I see you made it check all the .kt files instead of just the ones that changed.
> 
> Actually, this can be annoying, if `ktlint` behavior changes often. However, that should be rare.

It shouldn't change unless we update the version in our setup instructions. I don't think we've updated it so far, so it should be good. (We could also add a version check into sigh if we need to)

**Pull request merged**
