### PR TITLE
SearchTokensToParticles strategy to also find recipe by name

### PR DESCRIPTION
**Pull request by mmandlis**

### CODE REVIEW

**Comment by mmandlis** [comment]
I tried to search for the "showlist" recipe, and this particular strategy seems to behave ok, but the type resolution isn't quite supporting it (yet?), resulting in:
recipe
  search `showlist`
    tokens // `showlist`
  ? as view0 // [~a]  // unresolved handle: unresolved type
  create as view1 // [~a]
  copy 'manifest:https://$cdn/artifacts/Products/Products.recipes::7:immediateShowProduct' as view2 // HostedParticleShape
  slot 'rootslotid-root' #root as slot1
  Multiplexer as particle0
    hostedParticle = view2
    list <- view0
    consume annotation as slot0
  ShowCollection as particle1
    collection <- view0
    descriptions -> view1
    consume master as slot1
    ... 
`
In theory, we could resolve the type based on the hosted particle -`ShowProduct`.. WDYT?

**Comment by shans** [comment]
Yeah, I think you're right. I'll try to make a minimal repro of the type problem.

Did you also want a review of this CL?

**Comment by shans** [comment]
OK, I think I understand what's going on here.

There isn't a concrete resolution for view0 - only a constraint. view0 has to be at LEAST a Product, but could be more constrained.

https://github.com/PolymerLabs/arcs/pull/1254 shows this in practice - while the view isn't resolved, it reports that it `canEnsureResolved()`, and `maybeEnsureResolved()` chooses a type for it.

We'll need to work out where this flow isn't happening in our codebase and update. I'll look into that next.

**Comment by mmandlis** [comment]
Thanks for looking into this. Let me know if you won't have time for this, i can try and figure it out myself.

And yes, please, take a look at this PR unrelated.

**Comment by shans** [comment]
It actually *does* resolve correctly in that test, I've updated it to show. Are you sure the problem here isn't that the handle is unresolved because the fate is unassigned?

**Comment by mmandlis** [comment]
Right, my bad, the unassigned fate would only try to default to `use` (won't it?), but should really be `map`... Do we have a strategy in mind that would have resolved it?

**Comment by shans** [comment]
I think it would probably default to `create`. Piotr is working on something that might help with this, I think.

**Pull request merged**
