### PR TITLE
Wraps webpack in bazel rules for javaharness

### PR DESCRIPTION
**Pull request by csilvestrini**
This greatly simplifies the javaharness workflow. Instead of having to
remember to webpack the various things (runtime, pipes-shell), bazel
will detect for you when sources change and will run the various webpack
scripts.

`./tools/sigh webpack` is given its own BUILD target in
`//tools:sigh_webpack`, and pipes-shell's `deploy.sh` script is given a
target in `//shells/pipes-shell:pipes_shell_web`.

Instructions for building javaharness have been updated, and the
unnecessary build.sh script and various symlinks removed.

### CODE REVIEW

**Comment by jasonwyatt** [comment]
I cloned your repo to a second location (to simulate a fresh install), imported into ASwB, and the ANDROID_HOME Issues returned. I wonder if there's something that can be fixed here which wouldn't require `bazel clean --expunge`?

**Comment by jasonwyatt** [comment]
Even `bazel clean --expunge` doesn't seem to help now. After running it, verifying ANDROID_HOME is configured (again), and using the "Sync" button in studio, I see:

```
Syncing project: Sync (incremental)...
Updating VCS...
Running Bazel info...
Command: bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --

Command: git diff --name-status --no-renames bcba2f4fabc111c33d35aea17da4af8f4c7c0761

DEBUG: Rule 'com_google_j2cl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "247a68d8a1d05029e8c23eadb17f2a681b14e49bcbacb5b5136d0b3cfbff2d57"
DEBUG: Call stack for the definition of repository 'com_google_j2cl' which is a http_archive (rule definition at /usr/local/google/home/jwf/.cache/bazel/_bazel_jwf/cdc16c4433faaa5fae0e2c735245c26d/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /usr/local/google/home/jwf/github/arcs2/WORKSPACE:88:1
DEBUG: Rule 'io_bazel_rules_closure' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "9d4b3af0efb86b4f3b1658d12ad485e089587b537bfee0474f2a8549ad1d7f2c"
DEBUG: Call stack for the definition of repository 'io_bazel_rules_closure' which is a http_archive (rule definition at /usr/local/google/home/jwf/.cache/bazel/_bazel_jwf/cdc16c4433faaa5fae0e2c735245c26d/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /usr/local/google/home/jwf/.cache/bazel/_bazel_jwf/cdc16c4433faaa5fae0e2c735245c26d/external/com_google_j2cl/build_defs/repository.bzl:25:5
 - /usr/local/google/home/jwf/.cache/bazel/_bazel_jwf/cdc16c4433faaa5fae0e2c735245c26d/external/com_google_j2cl/build_defs/repository.bzl:6:5
 - /usr/local/google/home/jwf/github/arcs2/WORKSPACE:102:1
DEBUG: Rule 'com_google_elemental2' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "afc7079a7ed5c3e491a75161e0b3376ff8c4e7e19c25f7a712f0c6061590322e"
DEBUG: Call stack for the definition of repository 'com_google_elemental2' which is a http_archive (rule definition at /usr/local/google/home/jwf/.cache/bazel/_bazel_jwf/cdc16c4433faaa5fae0e2c735245c26d/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /usr/local/google/home/jwf/github/arcs2/WORKSPACE:138:1
DEBUG: Rule 'com_google_jsinterop_generator' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "3268003494a10e858b6ca098c475ae36685f837c7639bc8ceb3019a83608a2d1"
DEBUG: Call stack for the definition of repository 'com_google_jsinterop_generator' which is a http_archive (rule definition at /usr/local/google/home/jwf/.cache/bazel/_bazel_jwf/cdc16c4433faaa5fae0e2c735245c26d/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /usr/local/google/home/jwf/.cache/bazel/_bazel_jwf/cdc16c4433faaa5fae0e2c735245c26d/external/com_google_elemental2/build_defs/repository.bzl:16:5
 - /usr/local/google/home/jwf/github/arcs2/WORKSPACE:146:1
Computing VCS working set...
Your working set is empty
Sync targets from project view targets:
  //javaharness/java/...
  //javaharness/javatests/...
  -javaharness/java/arcs/pipes-shell/...

Building Bazel targets...
Command: bazel build --tool_tag=ijwb:AndroidStudio --keep_going --build_event_binary_file=/tmp/intellij-bep-d9652f0b-93ee-4dcf-9140-6450c7a7bb58 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/opt/android-studio-with-blaze-3.5/plugins/aswb-blaze/aspect --output_groups=intellij-info-android,intellij-info-generic,intellij-info-java,intellij-resolve-android,intellij-resolve-java -- //javaharness/java/... //javaharness/javatests/... -javaharness/java/arcs/pipes-shell/...

Loading: 
Loading: 0 packages loaded
ERROR: Skipping 'javaharness/java/arcs/pipes-shell/...': no targets found beneath 'javaharness/java/arcs/pipes-shell'
WARNING: Target pattern parsing failed.
Analyzing: 15 targets (15 packages loaded, 0 targets configured)
ERROR: /usr/local/google/home/jwf/github/arcs2/WORKSPACE:40:1: //external:android/sdk depends on @androidsdk//:sdk in repository @androidsdk which failed to fetch. no such package '@androidsdk//': Either the path attribute of android_sdk_repository or the ANDROID_HOME environment variable must be set.
ERROR: /usr/local/google/home/jwf/github/arcs2/WORKSPACE:40:1: //external:android/dx_jar_import depends on @androidsdk//:dx_jar_import in repository @androidsdk which failed to fetch. no such package '@androidsdk//': Either the path attribute of android_sdk_repository or the ANDROID_HOME environment variable must be set.
Analyzing: 15 targets (48 packages loaded, 398 targets configured)
ERROR: /usr/local/google/home/jwf/github/arcs2/tools/BUILD:4:1: in run_in_repo rule //tools:sigh_webpack: 
Traceback (most recent call last):
	File "/usr/local/google/home/jwf/github/arcs2/tools/BUILD", line 4
		run_in_repo(name = 'sigh_webpack')
	File "/usr/local/google/home/jwf/github/arcs2/build_defs/run_in_repo.bzl", line 76, in _run_in_repo
		_write_shell_script(ctx = ctx, run_script = True)
	File "/usr/local/google/home/jwf/github/arcs2/build_defs/run_in_repo.bzl", line 26, in _write_shell_script
		fail("\n*****\nrepo_root is not defin...")

*****
repo_root is not defined. Run the following command from the root of your workspace:

echo "build --define=repo_root=$(pwd)" >> .bazelrc
*****

Analyzing: 15 targets (59 packages loaded, 973 targets configured)
Analyzing: 15 targets (70 packages loaded, 1025 targets configured)
Analyzing: 15 targets (70 packages loaded, 1025 targets configured)
WARNING: errors encountered while analyzing target '//javaharness/javatests/arcs/android/impl:AllTests': it will not be built
WARNING: errors encountered while analyzing target '//javaharness/javatests/arcs/crdt:AllTests': it will not be built
WARNING: errors encountered while analyzing target '//javaharness/java/arcs/android/demo/app:app': it will not be built
WARNING: errors encountered while analyzing target '//javaharness/java/arcs/demo/particles:particles-android': it will not be built
WARNING: errors encountered while analyzing target '//javaharness/java/arcs/android/api:api': it will not be built
WARNING: errors encountered while analyzing target '//javaharness/java/arcs/demo/ui:ui-android': it will not be built
WARNING: errors encountered while analyzing target '//javaharness/java/arcs/api:api-android': it will not be built
WARNING: errors encountered while analyzing target '//javaharness/javatests/arcs/api:AllTests': it will not be built
WARNING: errors encountered while analyzing target '//javaharness/java/arcs/demo/services:services-android': it will not be built
WARNING: errors encountered while analyzing target '//javaharness/java/arcs/android/client:client': it will not be built
WARNING: errors encountered while analyzing target '//javaharness/java/arcs/crdt:crdt-android': it will not be built
WARNING: errors encountered while analyzing target '//javaharness/java/arcs/android/demo/service:service': it will not be built
WARNING: errors encountered while analyzing target '//javaharness/java/arcs/android/impl:impl': it will not be built
WARNING: errors encountered while analyzing target '//javaharness/java/arcs/android/service:service': it will not be built
WARNING: errors encountered while analyzing target '//javaharness/java/arcs/android/demo/ui:ui': it will not be built
INFO: Analyzed 15 targets (71 packages loaded, 1213 targets configured).
INFO: Found 0 targets...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: command succeeded, but there were errors parsing the target pattern
INFO: Elapsed time: 6.500s, Critical Path: 0.02s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully
build invocation result: build_error
Sync was successful, but there were Bazel build errors. The project may not be fully updated or resolve until fixed. If the errors are from your working set, please uncheck 'Bazel > Sync > Expand Sync to Working Set' and try again.
Parsing build outputs...
Total rules: 0, new/changed: 0, removed: 0
Reading IDE info result...
Updating target map
Loaded 0 aspect files, total size 0kB
Target map size: 0
Reading jdeps files...
Loaded 0 jdeps files, total size 0kB
Reading package manifests...
Java content entry count: 2
Updating Unpacked AAR libraries...
Updating Objfs file watcher...
Updating Jar Cache...
Total Jar Cache size: 0 kB (0 files)
Prefetching files...
Refreshing files
Computing directory structure...
Committing project structure...
Workspace has 0 libraries
Android resource module count: 0, run config modules: 0, order entries: 0, generated resources: 0
Workspace has 2 modules
Updating in-memory state...
Could not read from manifest file: /usr/local/google/home/jwf/github/arcs2/AndroidManifest.xml
Sync finished

Timing summary:
BlazeInvocation: 6.6s, Prefetching: 0ms, Other: 23ms
```

**Comment by jasonwyatt** [comment]
FWIW, things work fine from the command line and only seem to fail from Android Studio.

**Comment by csilvestrini** [comment]
```
repo_root is not defined. Run the following command from the root of your workspace:

echo "build --define=repo_root=$(pwd)" >> .bazelrc
```

Did you try doing that?

**Pull request merged**
