### PR TITLE
Disable NPM Cache

### PR DESCRIPTION
**Pull request by alxrsngrtn**

### CODE REVIEW

**Comment by alxrsngrtn** [comment]
No problem!

**Comment by shaper** [comment]
> Can you remove the disk-cache stuff from docker too please?

Is removing it the right thing to do? That disk-cache stuff is stated as being bazel related. How/if that relates to the npm caching is not clear to me.

**Comment by shaper** [comment]
> > Can you remove the disk-cache stuff from docker too please?
> 
> Is removing it the right thing to do? That disk-cache stuff is stated as being bazel related. How/if that relates to the npm caching is not clear to me.

It could also be best to change one thing at a time (unless disabling the npm cache and leaving the disk-cache stuff is expected to be busted in some manner).

**Comment by csilvestrini** [comment]
> > > Can you remove the disk-cache stuff from docker too please?
> > 
> > 
> > Is removing it the right thing to do? That disk-cache stuff is stated as being bazel related. How/if that relates to the npm caching is not clear to me.
> 
> It could also be best to change one thing at a time (unless disabling the npm cache and leaving the disk-cache stuff is expected to be busted in some manner).

One thing at a time sgtm.

AFAIK the disk-cache stuff was added to our Docker setup so that Travis would cache our bazel artifacts for us. I'm not sure that that ever actually worked.

I just don't want us to forget to clean that all up.

**Comment by shaper** [comment]
Alex is OOO til Tue so I will clone this to a new PR to land.

**Comment by shaper** [comment]
Closing in favor of https://github.com/PolymerLabs/arcs/pull/4468

**Pull request closed without merging**
