### PR TITLE
Remove unused particles and add Chooser with checkboxes

### PR DESCRIPTION
**Pull request by mmandlis**
Just as an experiment I added an alternative Chooser particles that has checkboxes next to each option, and single button to submit all selected.

### CODE REVIEW

**Comment by mmandlis** [comment]
The travis complains about failing tests, however I ran
(cd runtime && npm install && npm test)
locally and it succeeded.

**Comment by dstockwell** [comment]
> The travis complains about failing tests, however I ran
> (cd runtime && npm install && npm test)
> locally and it succeeded.

For the time being, particles won't be able to depend on tracing.

To get into the same state locally, remove the `node_modules` directory from `/tracelib` and `/runtime`.

**Comment by mmandlis** [comment]
Thanks Doug, all tests are passing now, please, take another look.

PS: browserify doesn't work though, I'm looking into it, but it shouldn't affect this change, because my recent commit only removed requiring tracelib.

**Comment by mmandlis** [comment]
I merged the recent changes and tests in the browser, everything works as expected (I commented it out in the browser-test though, to avoid unnecessary changes to it.

**Pull request merged**
