### PR TITLE
Disable flaky allocator e2e tests

### PR DESCRIPTION
**Pull request by csilvestrini**

### CODE REVIEW

**Comment by yuangu-google** [comment]
Can you attach the corresponding Firebase Test Lab run link or logs to the bug filed? Otherwise it'll be hard to see why it's flaky.

**Comment by csilvestrini** [comment]
https://firebase.corp.google.com/project/arcs-265404/testlab/histories/bh.2c69c48d48bfc074/matrices/8158749980681589992

I'll comment on the bug too

**Comment by yuangu-google** [comment]
Also testAllocator_persistentReadWrite seems passing from the last master run: https://pantheon.corp.google.com/cloud-build/builds/b54bd3de-2bda-4374-bf96-a94d8327a9b2;step=5?project=arcs-265404

Why are you disabling it?

**Comment by csilvestrini** [comment]
> I'll comment on the bug too

Never mind, you already did, thanks!

**Comment by csilvestrini** [comment]
> Also testAllocator_persistentReadWrite seems passing from the last master run: https://pantheon.corp.google.com/cloud-build/builds/b54bd3de-2bda-4374-bf96-a94d8327a9b2;step=5?project=arcs-265404
> 
> Why are you disabling it?

Failing here: https://firebase.corp.google.com/project/arcs-265404/testlab/histories/bh.2c69c48d48bfc074/matrices/5038745902115553524/executions/bs.d8f2462b2f0dc14b

So it seems to be flaky too

**Pull request merged**
