### PR TITLE
Support for Nullable fields

### PR DESCRIPTION
**Pull request by Cypher1**
Adds support for nullable fields in Javascript and Kotlin

Outstanding work (i.e. TODOs):
- Workout how to turn on the nullableSupport flag for code generation when testing it (without enabling for all)
- Tests for nullable values: serialization, etc
- Enforcing non-nullable values are unset
- Test that non-null values that happen to be defaults are set in the DB

(i.e. x: Number? = 0 -> x should be stored to the DB, x:Number = 0 -> x doesn't need to be stored, x: Number? = null -> x doesn't need to be stored)

- Double check (and ideally test) Parcelable round trips
- Nullable Showcase
- Turn on the flag 'for real'

Once each of those are done the support will be considered landed (and I'll start looking for feedback)

### CODE REVIEW

**Comment by csilvestrini** [comment]
> x:Number = 0 -> x doesn't need to be stored

I don't think it hurts to store this. That would allow you to safely change a schema field from non-nullable to nullable and have everything continue working. If you don't store the default value then you can't do that migration.

**Review by csilvestrini — CHANGES_REQUESTED** [review]
Could you please split this up into smaller PRs? It's too long to review as it is, and it's much easier to identify problems and roll them back when the PRs are small and focussed.

One obvious standalone PR would be to add the Kotlin `FieldType.NullableOf` (with conversion functions for proto/parcelable). The EntityBase stuff could go after that in another PR. The TypeScript code could go in its own PR.

**Comment by Cypher1** [comment]
Sure thing @csilvestrini just got to find ways to make the sub-commits pass tests without each other.
Should be able to do that tomorrow :)

**Comment by Cypher1** [comment]
Realised cl/356612397 hasn't landed yet which also makes this PR look larger than it really is.

Will wait for it to be merged and then upload the split PRs

**Pull request closed without merging**
