### PR TITLE
Upgrade outdated node-fetch dependency from 1.7.2 to 2.2.1

### PR DESCRIPTION
**Pull request by lindner**
- Upgrade Guide: https://github.com/bitinn/node-fetch/blob/master/UPGRADE-GUIDE.md
- Changelog: https://github.com/bitinn/node-fetch/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by lindner** [comment]
of course it appears that runtime/fetch-{node,web}.js is unused, but maybe we want it for the future...

**Comment by shans** [comment]
Sorry, I must have missed this. Still want to land?

**Comment by lindner** [comment]
This version has issues, so I have shelved this for now.

**Comment by shans** [comment]
Ah cool. OK for me to close then?

**Comment by lindner** [comment]
node-fetch 2.2.1 fixed the underlying issue in https://github.com/bitinn/node-fetch/issues/502

PR updated and now working.

**Comment by lindner** [comment]
This one is ready to submit now that the underlying issue is fixed.

**Pull request merged**
