### PR TITLE
Move VolatileStorageKey into its own file

### PR DESCRIPTION
**Pull request by mmandlis**

### CODE REVIEW

**Comment by mmandlis** [comment]
If that looks fine, I'll do the same for ramdisk and database, and move the CapabilitiesResolver registration into the same central place where the parsers are registered.

**Comment by cromwellian** [comment]
I feel if we end up with a bunch of different keys, we might want to move the storage_key target into a separate package, like. java/arcs/core/storage/keys

**Comment by mmandlis** [comment]
Jason is ooo, i would like to proceed with this somehow until there are tons of conflicts to resolve... Can we reach a consensus? I'm happy to create a `keys` package like Ray is proposing, if that's what we think is best...

**Comment by mmandlis** [comment]
> I think this is fine, if you want you can do the keys package as a follow on, I just know from experience, Cameron prefers subpackages to build targets.

@csilvestrini WDYT?
I'd rather do the change as we want it to begin with.

**Comment by csilvestrini** [comment]
An `arcs.core.storage.keys` package would be ideal, I think.

**Comment by mmandlis** [comment]
I created the subpackage, and also moved the Ramdisk and Database key.
Manual copybara (still running): 300256075.
Probably ReferenceModeStorageKey needs to be moved as well (in a followup PR)
PTAL

**Pull request merged**
