### PR TITLE
Move javaharness code under //{java,javatests}.

### PR DESCRIPTION
**Pull request by shaper**
Part 4 from [the plan](https://docs.google.com/document/d/1lrq-RE5UEWtgFyRR_GBnySGaJYSjwzPzKcckniojPRU/edit#heading=h.9sb71nh8c7ud)

Notes:
- we may want to rename `arcs.sdk.android.dev.android` to `arcs.sdk.android.dev.impl` (or just move all files there up a directory, or open to other thoughts), since it's got `android` in there 2x. We've also got `arcs.sdk.android.dev.api`. These were respectively, previously, `arcs.android` and `arcs.api` when under `javaharness`. I am following the document plan proposal by "moving `javaharness` under `{java,javatests}/arcs/sdk/android/dev`.
- there were a few scripts and README in `javaharness`, I've moved them under `java`. @mmandlis @csilvestrini should review and we can revise/delete/etc.

Both of above seem fine to do in subsequent changes as needed.

### CODE REVIEW

**Comment by ianull** [comment]
The modules at javaharness/java/arcs/android/... are for builing Arcs android service afaik.
So how about naming it services instead of 2x android?

java/arcs/sdk/android/dev/... is kinda deep :-)
Imho we have java/arcs/sdk/android & java/arcs/android at this point.
How about considering 
javaharness/java/arcs/android/ -> java/arcs/android/services
javaharness/java/arcs/api/ -> java/arcs/sdk/android/{api or common}
Let BUILD file multiplex devex and prodex.

Leave you guys to make a final call :p

**Comment by shaper** [comment]
I don't know that we want BUILD to mux, since we will want the ability if we choose to use it to build both DevEx and ProdEx into a single binary.

There's more on the directory thinking in the doc linked from the referenced issue, but I hear your points. Let's see what @csilvestrini and @piotrswigon think. Also I'm open to renaming further later, the primary thing is to get it out of `javaharness` which is super confusing.

Having `android` in the package/path twice is the really wonky thing but again could fix later.

**Comment by mmandlis** [comment]
- The README file should be updated (it currently uses the javaharness terminology) and I think moved to java/arcs/sdk/android/dev/ (or even java/arcs/sdk/android/dev/android).
- the 2x android is indeed confusing, so maybe java/arcs/sdk/android/dev/services, like Ian suggested? 

Also everything from javaharness is in /dev/ package, while some of the classes might not be dev specific (like CollectionProxy) + also there is some of the /api/ stuff doesn't belong under /sdk/, but these are (mostly? all?) duplicates for Java and Kotlin (like the Type stuff - CollectionType, EntityType, and CollectionProxy etc), so I'm hoping we can deprecated the Java ones, so it won't be an issue for a long time. 

Otherwise LGTM.

**Comment by csilvestrini** [comment]
Putting this all under `arcs.sdk.android.dev` sounds good to me. `arcs.sdk.android.dev.android` is pretty weird. A `service` subpackage would be find too (not `services`, since we already have a `arcs.sdk.android.storage.service` package, so let's be consistent with that).

> I don't know that we want BUILD to mux, since we will want the ability if we choose to use it to build both DevEx and ProdEx into a single binary.

I'd prefer to keep the DevEx stuff in its own package, if that's possible. I think it will be important to know which sources are DevEx-only. Also, it will be easier to enforce dependency ordering with BUILD rules that way.

> Also I'm open to renaming further later, the primary thing is to get it out of javaharness which is super confusing.

I agree. Once everything is in the same directory tree, it will be much easier to move subpackages around to improve things further.

**Comment by piotrswigon** [comment]
+1 to all said. Let's rename the second android to service or impl in a follow up CL.

**Comment by shaper** [comment]
I'll update the PR tomorrow to reflect feedback.

**Comment by shaper** [comment]
> * The README file should be updated (it currently uses the javaharness terminology) and I think moved to java/arcs/sdk/android/dev/ (or even java/arcs/sdk/android/dev/android).

I moved it to `java/arcs/sdk/android/dev/service` but it looks super out of date, can you take a look at it and revise as appropriate? I feel like most all of it has been replaced by other setup/install instructions, except it has a chunk at the end about ALDS and Arcs Cache Manager which seems worth preserving but I'm not sure whether this is still the best place for it. @ianull @piotrswigon as FYI as well.

> * the 2x android is indeed confusing, so maybe java/arcs/sdk/android/dev/services, like Ian suggested?

I moved things to `java/arcs/sdk/android/dev/services` rather than `java/arcs/sdk/android/dev/android` within this updated PR.

> Also everything from javaharness is in /dev/ package, while some of the classes might not be dev specific (like CollectionProxy) + also there is some of the /api/ stuff doesn't belong under /sdk/, but these are (mostly? all?) duplicates for Java and Kotlin (like the Type stuff - CollectionType, EntityType, and CollectionProxy etc), so I'm hoping we can deprecated the Java ones, so it won't be an issue for a long time.

Deprecate all of the things... I support actually putting a @Deprecated tag on them if they're deprecated.

**Comment by shaper** [comment]
> I moved things to `java/arcs/sdk/android/dev/services` rather than `java/arcs/sdk/android/dev/android` within this updated PR.

I mean `java/arcs/sdk/android/dev/service` (singular, following @csilvestrini note), above pluralization was a typo.

**Comment by piotrswigon** [comment]
Woohoo!

**Pull request merged**
