### PR TITLE
Throw import error on failed particle import

### PR DESCRIPTION
**Pull request by Cypher1**
Working on improving the error messages when importing particles that are somehow malformed.

Discovered in https://github.com/PolymerLabs/arcs/issues/3603.

### CODE REVIEW

**Comment by piotrswigon** [comment]
Haha, I've tried something similar in #3661 , one PR number apart :)

You're right that we should put cleaning up in finally.

I'm wondering however whether see the line number in the particle if you throw a new error, like you do now. In my PR I've attached the screenshots of the console, and it shows that on the right hand side Chrome can display the line number in the particle. Does it work the same way with your code?

Screen Shot 2019-09-30 at 10 47 18 pm

**Comment by mykmartin** [comment]
Piotr: that's a better way to set up the exception. Josh: we still want to
remove the "!clazz" check in particle-execution-context.ts

**Comment by piotrswigon** [comment]
@mykmartin : Maybe it is better in an abstract sense, but in practice Chrome is doing extra bookkeeping of exceptions and keeps metadata that is printed when it logs a thrown exception. This metadata is lost when you toString() an exception.

In practice if you do it the way it's done in this PR, you lose the line number from the particle, and you have to search for the error. Error shows up this way in the console:
Screen Shot 2019-10-01 at 5 14 52 pm

While if you re-throw the original exception, you do get a line count from the particle on the right hand side. The data is not on the error object, but remembered by Chrome and logged:
Screen Shot 2019-10-01 at 5 15 22 pm

**Comment by mykmartin** [comment]
I'm not sure I follow, Piotr. My comment was that the way you've done it is better ... isn't that what you're saying?

**Comment by Cypher1** [comment]
I would prefer to just rethrow to keep the original error, but I'd also like to give the user information about the source of the error (the particle id and recipe if possible), can we do both?

@mykmartin I didn't remove the `!clazz` check because there are ways for clazz to be undefined (other than an exception being thrown), one is for the particle code to not actually call define particle.

I believe this deserves an error message of its own.

**Comment by mykmartin** [comment]
Ok, just to close the loop: we all agree that the submitted change #3660 is better because it re-throws, and I agree with Josh that leaving the `!clazz` check is fine. :)

**Comment by Cypher1** [comment]
Thanks all (closing).

**Pull request closed without merging**
