### PR TITLE
Use LruCacheMap for StoreRecord, default capacity=100

### PR DESCRIPTION
**Pull request by cromwellian**

### CODE REVIEW

**Comment by ianull** [comment]
Nice!
I'd like to ensure the evicted stores don't cause any troubles.
Would you mind setting the capacity to 1 and run tests locally to see how it goes?

@galganif please confirm that the evicted stores don't cause any surprises like missing model update notifications, references gone invalid suddenly, etc.

**Comment by cromwellian** [comment]
> Nice!
> I'd like to ensure the evicted stores don't cause any troubles.
> Would you mind setting the capacity to 1 and run tests locally to see how it goes?
> 
> @galganif please confirm that the evicted stores don't cause any surprises like missing model update notifications, references gone invalid suddenly, etc.

Yeah, I'll run a test with cap=1 with the memory test and do a heap dump measurement as well

**Comment by galganif** [comment]
> @galganif please confirm that the evicted stores don't cause any surprises like missing model update notifications, references gone invalid suddenly, etc.

I think this is fine, if a store is missing from the map it can get re-created without problems. I agree with Ian it would be good, alongside the memory app, to run normal unit tests with cap=1. Eg set cap=1 in this pr to confirm gcb and copybara are happy, then revert it before merging.

**Pull request merged**
