### PR TITLE
update npm packages

### PR DESCRIPTION
**Pull request by smalls**
Using `npm update`. Also, an attempt to resolve hash differences (SHA1
vs SHA512) in `package-lock.json` following instructions here:
https://github.com/npm/npm/issues/16938#issuecomment-339863980

The tests are clean after this change.

### CODE REVIEW

**Comment by smalls** [comment]
This was an attempt to deal with `npm i` updating `package-lock.json` after every run. Those are the instructions at npm/npm#16938 (comment), but it seemed like a good time to update our packages as well.

**Comment by shaper** [comment]
Thought from in person discussion was to consider adding to sigh the notion of a canonical known-good npm/nvm version, and checking that at sigh start, and if not matching exactly then output a warning, and include a note that for now unstable integrity hashes for npm can be resolved by matching those versions and clearing cache as described in the linked comment above.

**Comment by smalls** [comment]
If you're bothered by SHA differences in `package-lock.json` changes, this worked for me and @shaper (instructions link above):

1. Update to this patch.
1. Update to npm 5.7.1 & node 9.2.0
1. `rm -rf node_modules`
1. `npm cache clean --force`
1. Revert any local changes to `package-lock.json`
1. `npm i`

Probably don't be concerned about this message? My system hasn't melted yet.
```
> npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
```

**Comment by shaper** [comment]
https://github.com/npm/npm/issues/19356#issuecomment-367607716 is the other issue we'd discussed previously around unstable pruning behavior, and claims fixed in npm v5.7.

**Comment by smalls** [comment]
Oh, so maybe this was a one-time thing and once we're all on 5.7 this'll be done!

**Comment by mykmartin** [comment]
Just tried to follow this process and received an error. I'm on node v9.4.0, if that makes any difference.

...
23276 silly extract firebase@4.11.0
23277 silly pacote trying firebase@4.11.0 by hash: sha512-G1fX9+q3YXjdz3Wdmq7TM3EmLnxSmhsZtOyyhKg5hYfHi0XoOyQrva/JJmROQ+Dz2Ku+hWpi8tUwOCt7uxKfng==
23278 silly pacote data for sha512-G1fX9+q3YXjdz3Wdmq7TM3EmLnxSmhsZtOyyhKg5hYfHi0XoOyQrva/JJmROQ+Dz2Ku+hWpi8tUwOCt7uxKfng== not present. Using manifest.
23279 verbose stack Error [ERR_STREAM_WRITE_AFTER_END]: write after end
23279 verbose stack     at writeAfterEnd (_stream_writable.js:237:12)
23279 verbose stack     at PassThrough.Writable.write (_stream_writable.js:287:5)
23279 verbose stack     at PassThrough.Writable.end (_stream_writable.js:573:10)
23279 verbose stack     at ReadEntry.entry.on (/usr/local/google/home/mykmartin/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
23279 verbose stack     at ReadEntry.emit (events.js:165:20)
23279 verbose stack     at ReadEntry.emit (/usr/local/google/home/mykmartin/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
23279 verbose stack     at ReadEntry.[maybeEmitEnd] (/usr/local/google/home/mykmartin/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
23279 verbose stack     at ReadEntry.end (/usr/local/google/home/mykmartin/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
23279 verbose stack     at Unpack.[consumeBody] (/usr/local/google/home/mykmartin/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
23279 verbose stack     at Unpack.[consumeChunkSub] (/usr/local/google/home/mykmartin/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
23279 verbose stack     at Unpack.[consumeChunk] (/usr/local/google/home/mykmartin/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
23279 verbose stack     at Unzip.(anonymous function).on.chunk (/usr/local/google/home/mykmartin/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
23279 verbose stack     at Unzip.emit (events.js:160:13)
23279 verbose stack     at Unzip.emit (/usr/local/google/home/mykmartin/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
23279 verbose stack     at Unzip.write (/usr/local/google/home/mykmartin/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
23279 verbose stack     at Unzip.write (/usr/local/google/home/mykmartin/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
23280 verbose cwd /usr/local/google/home/mykmartin/code/arcs
23281 verbose Linux 4.9.0-5-amd64
23282 verbose argv "/usr/local/google/home/mykmartin/.nvm/versions/node/v9.4.0/bin/node" "/usr/local/google/home/mykmartin/.nvm/versions/node/v9.4.0/bin/npm" "install"
23283 verbose node v9.4.0
23284 verbose npm  v5.7.1
23285 error code ERR_STREAM_WRITE_AFTER_END
23286 error write after end

**Comment by smalls** [comment]
There's some discussion of a very similar sounding bug over in an npm issue (https://github.com/npm/npm/issues/19989). It's weird (but fortunate) that it worked after a retry.

**Pull request merged**
