### PR TITLE
Add Paxel latency and entity count logging.

### PR DESCRIPTION
**Pull request by yuangu-google**

### CODE REVIEW

**Review by piotrswigon — COMMENTED** [review]
Great!

One request could be about testing. We have EvaluatorParticleTest.kt set up, and there's a bunch of interesting tests there. If you have some Fake for `Analytics` (or a Mock) it should be trivial to use it in tests and add a few tests for checking that counts produced are correct.

They obviously will be, as code it rather simple, but it is worth having tests for ensuring the behavior does not change.

WDYT?

**Comment by yuangu-google** [comment]
Sure, I love tests.

**Comment by yuangu-google** [comment]
PTAL thanks.

**Review by piotrswigon — APPROVED** [review]
Thanks!

**Pull request closed without merging**
