### PR TITLE
Check for existence of particle impl

### PR DESCRIPTION
**Pull request by piotrswigon**
@sjmiles `PipeEntityReceiver.js` is referenced but not found, can you help?

### CODE REVIEW

**Comment by sjmiles** [comment]
I tend to leave artifacts around that I plan to revitalize and/or refer to in the near future. I didn't realize there was a zero-tolerance policy. 

It may take me a few days to collect the material off repo.

**Comment by sjmiles** [comment]
You can delete Demo/PipeDemo.recipe and it's reference from Demo/Demo.recipes.

I'll rebuild it later.

**Comment by sjmiles** [comment]
Also, Profile/Geolcation.schema has some non-schema dross inside that should be deleted.

**Comment by csilvestrini** [comment]
I didn't mean to be a nuisance with these tests, I just wanted to prevent particles from accidentally breaking over time.

If you'd rather keep around recipes/particles that don't currently work, you can give them some non-standard extension, e.g. PipeDemo.recipe.draft or something like that, then the test should skip over them.

**Comment by sjmiles** [comment]
No problem, we can just delete the files. I would have done this, but then I would have to push to the PR, seems best the author takes care of it (@piotrswigon?).

**Comment by piotrswigon** [comment]
Thanks @sjmiles for recommendations!

**Comment by sjmiles** [comment]
Thanks for the cleanups guys.

**Pull request merged**
