### PR TITLE
solo overrides dynamic manifest

### PR DESCRIPTION
**Pull request by ianull**
Currently connecting to host pipes-shell doesn't work at the demo app
via the url http://localhost:8786/...?solo=<manifest> since the dynamic
manifest via bus.dispatcher.configure always overrides the solo argument
but the demo_manifest_bundle.arcs is not generated during web depolyment
via the deploy.sh script.

Let the solo argument override dynamic manifest provides the flexibility
of exercising new features before bundling and deploying them via dynamic
manifest in app assets.

Tests are done for Autofill and Renderer via the urls:
file:///android_asset/arcs/index.html?
http://localhost:8786/shells/pipes-shell/web/deploy/dist/?solo=canonical.manifest&

### CODE REVIEW

**Comment by ianull** [comment]
Hey guys,

Does the change make sense to you in terms of usage of dynamic manifest?
I cooked this since the remote pipes-shell does not work at all at ToT.

**Comment by sjmiles** [comment]
Would it work if we renamed `canonical.manifest` to `demo_manifest_bundle.arcs`? I'd like to get rid of the `solo` machinery if we can.

If that's not a good solution, I'm ok with the fixes here.

**Comment by ianull** [comment]
I thought about it at the first place but realized soon that the demo_manifest_bundle.arcs is generated at per-app-bundle build rule
arcs_manifest_bundle(
    name = "demo_manifest_bundle",
    ...
)

Each app can give their own manifest bundle name which then is used for looking up dynamic manifest. So the manifest demo_manifest_bundle.arcs can only work for the demo app.

**Comment by ianull** [comment]
So imo the quickest fix is still keeping the solo which overrides the dynamic manifest.
The other slow fix is figuring out a way of scanning and generating the corresponding xxx.arcs files for all arcs_manifest_bundle rules when executing web/depoly.sh

**Comment by sjmiles** [comment]
Ok, I'm not clear on why some deployments have a constructed manifest and some don't. 
Also it's my understanding that the `deploy.sh` is going to be changed so that the dist includes no particle artifacts, so that might impact `canonical.manifest`.

But clearly this change is a problem solver for you, so it's ok by me.

**Comment by sjmiles** [comment]
Fwiw, rebasing on master might fix the test; a Kotlin build problem was fixed yesterday afternoon.

**Comment by ianull** [comment]
Thanks, Scott.
Definitely the deployment process will be changed over time.
I just bring what should have worked back again for quicker Arcs exercising (at least for myself :p)

The Travis failure seems like a new failure cuz I rebased just within one hour.

**Comment by sjmiles** [comment]
> I just bring what should have worked back again for quicker Arcs exercising (at least for myself :p)
Yep, sounds good. Sorry I guessed wrong on the override order!

> The Travis failure seems like a new failure cuz I rebased just with in one hour.
Dang.

**Pull request merged**
