### PR TITLE
AddUseHandles -> AddMissingHandles, refactor HandleMapperBase strategies, delete FallbackFate

### PR DESCRIPTION
**Pull request by mmandlis**
Described in more detail in: https://docs.google.com/document/d/19QixNPDuDVRmDvKmKqoI2VnPHOOOnQ_jVU0NXz8mocE/edit#heading=h.9aa09nxvdzfj
Also fixes: https://github.com/PolymerLabs/arcs/issues/1413

### CODE REVIEW

**Comment by shans** [comment]
This doesn't lead to a blowout in generated recipes? Looks like a nice simplification.

**Comment by mmandlis** [comment]
It does produce more recipes. It will produce even more recipes when we have more stuff in the context (for example, now it doesn't only suggest finding restaurants near `my` location, but also Claire's location, because Claire is a person and is in the context). 
So we'll need ranking sooner rather than later. But it seems like the right direction anyway.

Alternatively (or if/when this does explode), it is possible to tweak the assign-handles strategy to prefer `use` fate, if possible, otherwise fallback to `map/copy` (this will be closer to today's behavior, but more consistent).

Let me know, if you prefer just merging it as is, or with this more conservative alternative.

**Comment by shans** [comment]
I think this is sort of another example of us going around in circles then.

Preferring a fate => less recipes, but we don't capture every use case.
Exploding the fates => too many recipes.

We can't just keep going backwards and forwards on this. Like with the other parts of the coalescing doc, we need to take a step back and work out what other signals we can use to intelligently decide whether to go with use, map or copy.

In terms of this specific patch, if it isn't causing an explosion right now, I don't mind if it gets merged. I just don't see this as evidence of us progressing towards a more correct place.

**Comment by mmandlis** [comment]
I don't necessarily agree. I think this is better because:
- it doesn't do unpredictable confusing wrong stuff, like when fate was set to default `use`, but then fallback to `map/copy`, and then failed to coalesce (because we only coalesce terminal recipes with `use` and `create`)
- the logic and structure of the code a more straight forward and easier to reason about
- but mainly, it produces good valid relevant recipes that weren't produced before, and what remains unimplemented is the ranking (but we never really explored it) - it is reasonable for me to want restaurants near Claire's location if Claire is in my context. This suggestion may be more or less relevant depending on our proximity and whether or not I have a meeting scheduled with Claire etc. But it is a valid suggestion.

Re explorations document - it's current goal is to track the changes I'm currently making and understand why they are being made. The stepping back and making intelligent decisions is next stage (at least this was my impression) - after we manage to make this work (so maybe like now? when this PR is submitted? :)) Let's chat in person on Monday?

**Comment by shans** [comment]
Right, in that regard it's an improvement. It's also a step backwards in the sense that we used to have this and changed it to what we have now.

If we keep cycling, by definition we're not improving.

**Pull request merged**
