### PR TITLE
Rename {inner,outer}-PEC.js towards improved self-documentation.

### PR DESCRIPTION
**Pull request by shaper**
For discussion, this PR:
- currently just renames the files
- but, I propose also renaming the classes `InnerPEC` to `ParticleExecutionContext`, and `OuterPEC` to `ParticleExecutionHost` (and will update PR if there's support)
- also overwrites the existing `ParticleExecutionContext` base class which appears to essentially be an abstract class or an interface that isn't actually used for a generalized purpose anywhere at this time
- even with the above, IMO I think it'd still be fine to use the `pec` member data abbreviation where we store instance references.

I know `PEC` is shorter and normally am a fan of such brevity but I support the discussion in the issue. But open to being convinced otherwise.

Fixes https://github.com/PolymerLabs/arcs/issues/488

### CODE REVIEW

**Comment by mmandlis** [comment]
I don't remember off the top of my head what was the purpose of the ParticleExecutionContext interface. I do think that inner/outer are counter intuitive, but i don't know if i like context / host any better. 
also i think we should do the file and class renames in the same PR - this isn't that much more work i think, but this transitional state is extra confusing.
this is my long way of saying, let's wait for Shane to decide :)

**Comment by shaper** [comment]
Yeah, to be clear my intent was to do it in the same PR, I just didn't want to piece together the extra perl renaming commands unless there was support for it...

**Comment by shaper** [comment]
Also it's cool if @shans wants to keep inner-PEC and outer-PEC etc. At minimum we'll be able to close the longstanding issue.

**Comment by shaper** [comment]
FTR further bulk edits often easily done via something like `find . -name "*.js" | egrep -v -e '(node_modules|bower)' | xargs perl -p -i -e 's/\/inner-PEC.js/\/particle-execution-context.js/'`though things can go south for overly generic names.

**Comment by shans** [comment]
The name proposals SGTM. You probably want to talk to @dstockwell about the ParticleExecutionContext base class and check the name change is OK with him.

FWIW:
* "outer" and "inner" don't seem unintuitive given their purpose?; but
* "host" and "context" are significantly clearer.

**Comment by shaper** [comment]
I pinged @dstockwell but it seems he's away, the `particle-execution-context.js` in ToT was created in Apr 2017 as a commit to sketch the early particle API and wasn't modified since so I think it was just early thinking that fell away from critical path. I think it's probably ok to land this and can modify further as more feedback develops.

**Comment by dstockwell** [comment]
All seems good 👍

**Pull request merged**
