### PR TITLE
Code from hackathon android project

### PR DESCRIPTION
**Pull request by sjmiles**
Merge the Android demo app that @csilvestrini (the heavy lifting), @SHeimlich, @mmandlis and @sjmiles built during hackathon, so we don't lose the goodies.

### CODE REVIEW

**Comment by sjmiles** [comment]
Fwiw, the `processSlot` function implements a _UiBroker_

https://github.com/PolymerLabs/arcs/pull/3541/files#diff-bea785b6b9fa79f2ccd575aaed35dea9R175

**Comment by csilvestrini** [comment]
Thanks Scott!

Is there somewhere else we could put it, to better reflect its demo status? A top level `android` directory looks very official. Is there a demos folder somewhere?

**Comment by sjmiles** [comment]
Hey @csilvestrini, I wedged myself on this PR thinking about what you said. Instead of that, I figured I would just merge it before it gets too stale, and we can move it as a second step.

I think maybe just a subfolder like `android/hackathon` might suffice, but I haven't got around to seeing if that messes up the AndroidStudio config, which is what I was blocking on.

**Comment by csilvestrini** [comment]
Moving in https://github.com/PolymerLabs/arcs/pull/3619

**Pull request merged**
