### PR TITLE
Moves RamSlotComposer to runtime/testing

### PR DESCRIPTION
**Pull request by piotrswigon**
For your consideration. I would like to use RamSlotComposer in `runtime/test`. WDYT?

### CODE REVIEW

**Comment by sjmiles** [comment]
The Context generating server uses RamSlotComposer as part of it's normal operation. For this reason, it seems improper to have it in `/testing`, unless we are forking it.

**Comment by sjmiles** [comment]
In my experience it's never ok to have production code in a `testing` folder. Maybe we should discuss with the team? Seems like it might be a policy thing. 

Re: forking, I suspect remote-planning and context-shell need the same *composer, in which case they should use a common file. It's less clear whether the object needed for testing is the same (after all, ram-composer evolved by removing testing affordances from the original mock-composer).

**Comment by mmandlis** [comment]
...
> Be it in tests or in the Context Server, RamSlotComposer represents our best strategy to date for DOM-free, Node-friendly slot composing. The reason I think it should be in `/testing` is that it is based on MockSlotDomConsumer, which is a testing infrastructure - it takes shortcuts causing it to sometimes _be wrong_ in how it composes slots. This also is a good reason to rename it to FakeSlotComposer FWIW.
...

maybe then we should have a Ram/FakeSlotDomConsumer? and we could at some point fix the _wrong_ implementation?

**Comment by piotrswigon** [comment]
I will abandon this PR then. Created #2202 instead.

**Pull request closed without merging**
