### PR TITLE
Don't ignore npm and yarn package lock files.

### PR DESCRIPTION
**Pull request by shaper**
From previous discussion with @sjmiles and review of documentation:

https://docs.npmjs.com/files/package-locks
https://yarnpkg.com/lang/en/docs/yarn-lock/

These seem like files we should not have in `.gitignore` and should commit to the repository.

### CODE REVIEW

**Comment by shaper** [comment]
Partly addresses https://github.com/PolymerLabs/arcs/issues/728

**Comment by smalls** [comment]
It seems that this is the recommended approach based on those URLs, but I'm curious if we chose to not check these in for a specific reason? @sjmiles or @dstockwell do either of you know the history here?

**Comment by shaper** [comment]
Yeah, here's the conversation I had with @sjmiles about this a week or two ago: https://github.com/PolymerLabs/arcs-cdn/pull/176#issuecomment-362015960

I think the issue is that what will happen without having them in `.gitignore` is that random team eng may run `npm install`, and get a newer version of a package, and the lock file will be updated, and then they'll see it as dirty in their local checkout and have to know to commit.

However, in the absence of checking in the lock files, my impression from the docs is that we can't be as confident that a checkout will build out of the box, since we could pull a newer version of a module that breaks things in some manner.

**Comment by smalls** [comment]
Having the history for the files show a consistent record of engineers (all engineers, not just a few who're working on the build) will go a long way to answering that question for new engineers.

That answers my question, thanks!

**Pull request merged**
