### PR TITLE
(draft) particle and recipe unification proposal

### PR DESCRIPTION
**Pull request by mmandlis**
I'm sorry, this is a messy and long doc with a lot of babbling around...
But i might be on to something here, and if it makes any sense at all, i was hoping you could help me crystallize it.

### CODE REVIEW

**Comment by seefeldb** [comment]
Hah, no actually I love this! :)

The insight is in some way analogous to the insight behind unification of slots and handles: It turned out the difference is the type of connection, not the underlying node, e.g. `in`, `out`, `inout` being the part that's specific to handles, `compose`, `provide` what's specific to slots, but in some circumstances 'compose into this handle' making sense.

My worry with that unification was that for developers treating handles and slots differently makes things much easier to understand. The underlying symmetries are then for advanced developers.


I think there is something analogous to both here, and it's the relationship between a set of [often abstract] connections (how we're seeing today's recipes) and interfaces + the syntax:
 - Recipes can have interfaces
 - Particles are recipes with interface definitions and a concrete implementation (<=> a concrete implementation can't be referenced without also defining the interface)
 - Recipes can have connections, which one can think of as the recipe's implementation [1]
 - Recipes can reference other interfaces together with connections – this is the new kind of connection (this is a recipe referring to another recipe/particle)
 - Recipes can use interfaces (formerly shapes) as a way to to ask for recipes to be matched there – this is that connection in the other direction!
 - A recipe can refer to an interface that itself specifies an interface it requests (functor) and then connect a specific recipe to it (e.g. a recipe using the multiplexer)
 - Recipes with connections but without interfaces get an implicit interface
 - verbs are a way to refer to interfaces without specifying a specific one, typically together with connections (though those can all be implicit). Because recipes with connections get an implicit interface if they don't have one, a verb can refer to either. Hence in a multiplexer setup, it's fine for the functor to set a requested interface and the recipe using it to just assign a verb to it.

Do I understand this right?


I do think developers have an easier time if we introduce particles and recipes separately as concept. Also, because of [1], I'd suggest using the `particle` keyword when defining such a recipe, i.e. must have implementation and an interface and must not have a connections.

[1] I therefore suggest to not allow recipes with concrete implementations _and_ connections and force a separation of that definition – otherwise it would mean something like that an implementation can only used with also these connections present, which we explored earlier this year and ran into trouble with. We can explore that again, if we want, but out-of-scope for this round, ok?

**Comment by shans** [comment]
Link to doc: https://docs.google.com/document/d/1Oe0AzYVSanaxui3KDyimND7ttu7BWFEHIKmBmxAbvHg/edit#

**Comment by mmandlis** [comment]
advice needed re technicality - should i merge this PR? I noticed that design-docs-index.md moved to README, i can move the unification doc there. Should i add also the rest of the recipe related design docs ? thanks.

**Comment by piotrswigon** [comment]
(Attempting to settle this PR as part of P2 rotation)
@shans - as the owner of this process.

I think we should merge documents that describe designs that we're confident about implementing, so that people can refer back to them to understand parts of the system.

Does this document apply? I think the team agreed with the main idea of a doc and disagreed about some details. @mmandlis do we think people should re-read this proposal a 6 months from now? I'm not sure, but I would lean to merging more concrete design proposals and leave out the proposals that are meant as discussion starters.

WDYT?

**Comment by mmandlis** [comment]
I'm ok either way - I'm happy to delete this PR, or can reorganize the doc to mark which ideas we agreed/disagreed on, or anything in between. In general, I think we'll need to clean up this file periodically either way, as the system evolves.

Unrelated I also wonder whether we should start grouping the docs by subject in the readme file.

**Comment by shans** [comment]
I think that there's a category of design documentation that pertains to designs that are actively being worked on by multiple people. This - and several other documents - should be combined together and/or deleted, but probably not until design is complete.

**Comment by shans** [comment]
Good plan.

**Pull request closed without merging**
