### PR TITLE
add the extension unit tests to the travis build

### PR DESCRIPTION
**Pull request by smalls**

### CODE REVIEW

**Comment by smalls** [comment]
That second version works. I did change from 'gulp' to 'npm test' for runtime as well, but that appears to do the same thing. Any concerns @dstockwell?

**Comment by smalls** [comment]
Actually I wonder if 72ed224bf02649a8f7af4c96e91f99a0847ff8f2 already made this change. Let's discuss Monday.

**Comment by smalls** [comment]
Agreed, I found Doug's cl after I'd already put this up (just through happenstance, I was curious how his was coming along and saw a mention of a new build tool, sigh).

To see if this works, look at the 'All checks have passed' and click the 'Show all checks button'. One of the checks run is travis, looking at those details will tell you the specifics. Or just click this: https://travis-ci.org/PolymerLabs/arcs/builds/310269515?utm_source=github_status&utm_medium=notification.

(The first iteration here, 9cbd58f, didn't work. You can go back to that specific build as well and see the error).

**Comment by dstockwell** [comment]
> Actually I wonder if 72ed224 already made this change (or means we'll need to do something different here). Let's discuss Monday.

I didn't add any support for the web tests yet. I did move the main package file from `runtime`, so you'll need to update that line to `TESTDIR=.`

**Comment by smalls** [comment]
I've updated the cl to take the most recent changes into account. Let me know if this looks good.

@shaper, I misread your question. I don't know of a way to test without pushing, but you can enable travis on runs in repos associated with your user and you can squash commits so it doesn't look like you had to do a few iterations to get travis happy.

https://travis-ci.org/PolymerLabs/arcs
https://travis-ci.org/smalls/arcs

**Comment by smalls** [comment]
As an aside, web tests might be a misnomer.

There's a web test runner, but it's not required and just invokes regular mocha unit tests. One of the tests does parse a web page just for the schema.org parser but that's the extent of their web involvement. I am working on (struggling with) selenium tests for more traditional end-to-end web testing if that's what you were thinking of.

**Comment by dstockwell** [comment]
> As an aside, web tests might be a misnomer.

Maybe? I was referring to unit tests that require a browser context as web tests. Selenium is something different, usually painful 😉

**Comment by smalls** [comment]
Yes! I didn't realize that these actually already used a headless chrome, so it turns out that I was wrong and the nomer is not mis.

**Comment by smalls** [comment]
Well this merge went south. #546 is much cleaner.

**Pull request closed without merging**
