### PR TITLE
Add usages of ReadonlyMap where it's allowed

### PR DESCRIPTION
**Pull request by lindner**

### CODE REVIEW

**Comment by lindner** [comment]
Just an example of what this might look like.

Should we use this pattern?

**Comment by shans** [comment]
Yeah I think so. Maybe bring up on group chat to take other people's temperature?

**Comment by lindner** [comment]
No responses on group chat, but I know that @csilvestrini was saying we should move toward more immutability.

**Comment by csilvestrini** [comment]
Just seeing this now. I like it! :D

**Pull request merged**
